# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [2]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [29]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)
arr

# (a)
print('Shape is:', arr.shape)
print('Type is:', arr.dtype)
print('---------')

# (b)
print('Sum is:', arr.sum())
print('---------')

# (c)
print('Mean is:', arr.mean())
print('---------')

# (d)
arrzero= np.zeros((3, 5))
print(arrzero)
print('---------')

# (e)
arrones= np.ones((3, 5))
print(arrones)
print('---------')

# (f) 
arrsquares= np.square(arr)
print(arrsquares)
print('---------')

# (g)
newarray= arr.transpose()
y=np.dot(arr,newarray)
print(y)

Shape is: (3, 5)
Type is: int32
---------
Sum is: 105
---------
Mean is: 7.0
---------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
---------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
---------
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
---------
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [60]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows


# (a) 
print('Shape is:',df.shape)
print('---------')

# (b) 
print('Columns are:',df.columns)
print('---------')

# (c) 
print('3RD ELEMENT OF THE DATAFRAME IS 2ND INDEX:')
print(df.iloc[2])
print('---------')

# (d) 
dfspieces = df.groupby(['species'])
m= dfspieces.get_group('virginica')['petal_width'].mean()
print('Average of petal_width where species is virginica:',m)
print('---------')

# (e) 
dfspieces = df.groupby(['species'])
n= dfspieces.get_group('setosa')['sepal_width'].max()
print('Maximum of sepal_width where species is setosa:',n)
print('---------')

# (f): 
f= round(df.sepal_length.mean(),2)
print('Average value of sepal_length',f)
print('---------')

# (g): 
g= round(df.sepal_width.max(),2)
print('Max value of sepal_width',g)
print('---------')

# (h): 
h= round(df.petal_width.max(),2)
print('Min value of petal_width',h)

Shape is: (150, 5)
---------
Columns are: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
---------
3RD ELEMENT OF THE DATAFRAME IS 2ND INDEX:
sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dtype: object
---------
Average of petal_width where species is virginica: 2.026
---------
Maximum of sepal_width where species is setosa: 4.4
---------
Average value of sepal_length 5.84
---------
Max value of sepal_width 4.4
---------
Min value of petal_width 2.5


### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)


In [ ]:
1/ Global Information and Early warning System 

Data website name: I have found various data sets under the section “Global Information and Early warning System” namely Country Cereal Balance Sheet(CCBS), Domestic International Food Prices etc.
Data Description: Using the above data sets there can be plethora of information that can be inferred and jotted down to draw conclusions. Hence, data sets are generally referred to a collection of information. For example, Earth Observation data set provides us valuable information regarding condition of major food corps across the globe to assess production aspects. Earth Observation data majorly depends on indices like Agricultural Stress Index, Rain fall Estimates data, Progress of Season, Mean Vegetation Health index . These indices are termed as datum. Such information will lead us to identify agricultural areas that will be affected by dry spells or droughts in extreme cases. This will in turn help us to evaluate sustainable methods to avoid such extreme situations. These data sets include a wide variety collection of information on various aspects that effect the soil fertility. They are represented in the form of world maps with seasonal indicators that allow us to identify areas of croplands and grasslands with higher or lower likelihood of water stress.
Dataset Questions: 
•	What is the season during which there is huge water stress?
•	What are the areas that are widely prone for water stress?
•	What is the amount of rainfall in various areas?
•	What is the type of vegetation in and around the areas?
•	How long is the drought going to sustain?
 

2/ Airline On-Time Statistics and Delay Causes (2015 -2018) 
Data website name https://www.transtats.bts.gov/OT_Delay/OT_DelayCause1.asp
Data Description: This is the raw data set from the U.S. Department of Transportation's (DOT) Bureau of Transportation Statistics (BTS) to keep track of the efficiency performance of the domestic flights operated by large airlines. The information, which is published in the “Air Travel Consumer Report”, is categorized by the monthly number of on-time, delayed, canceled and diverted flights. 
Dataset Questions: 
•	What is the KEI of the each airlines and which airline is the most reliable?
•	What is the most common factor that causes flight delays? 
•	Are there any seasonal or geographical patterns between these delayed flights? 
•	What are the possible recommendations to improve performance of these flights ? 


3/ Crime Incident Reports (August 2015 - To Date) 
Dataset Website Name: https://data.boston.gov/dataset/crime-incident-reports-august-2015-to-date-source-new-system/resource/12cb3883-56f5-47de-afa5-3b1cf61b257b 
Dataset Description: crime incident reported in the city of Boston, from the year June 2015 to present. Data is extracted from Boston Police Department and focuses on capturing the classification of incident, Location Description, Incident Occurrence Date, Incident Description and shooting reports.
Dataset Questions: 
•	Which Day of Week has a higher chance of an incident occurring.
•	Which year had the highest records of incident reports.
•	Location incident hotspot (create a heat map)
•	Using the Uniform Crime Reporting (UCR) codes (law enforcement agencies use to classify criminal incidents when taking individual reports) – identify the classifications of crime Incident reported



